### PR TITLE
Hand detection 

### LINKED ISSUE #51: I want to add Hand Detection using mediapipe in your AI/ML section
Adding Hand detection in the AI/ML section of the repository using mediapipe and OpenCV

### PR DESCRIPTION
**Pull request by agneya-1402**
### Description
Hand detection using Mediapipe and OpenCV
Created in Collab notebooks

### Related Issue

Added Hand Detection in AI/ML section
This PR closes #51

### Motivation and Context
Adds hand detection using Google's AI and OpenCV framework

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by SVijayB** [comment]
Hey @agneya-1402 could you move the files into a folder called `Machine learning` ?
`Machine learning\Hand detection`

**Comment by agneya-1402** [comment]
Yes I did tried to commit my changes after adding it to AI/ML folder but its showing an error

Some checks were not successful
Greetings: All jobs have failed

I forked the project and cloned it in my machine, after adding the hand detection file i pushed the changes and tried to create a PR but it gave the above error

**Comment by SVijayB** [comment]
@agneya-1402 hey that's alright, the greetings workflow error is caused due to a different problem. No issues with your script.

**Comment by agneya-1402** [comment]
Hey, so what can I do to get my PR accepted ?

**Comment by SVijayB** [comment]
@agneya-1402 you know what, the code looks alright, I'll give you the hacktoberfest-accepted label, and that should work. I however don't think I'll be merging the PR. That cool?

**Pull request closed without merging**
