### PR TITLE
Adding stack function 

### PR DESCRIPTION
**Pull request by Nish251103**
### Description

i added a stack function of list. It.s a new feature to be used over a list as a basic function the function like push, pop, peek, display

### Related Issue

This PR closes # 

### Motivation and Context

It helps to perform stacks in a list like push, pop, peek and display
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by SVijayB** [comment]
Hey, please do not modify the pull_request_template.md file. Remove that and I will merge your PR.

**Comment by Nish251103** [comment]
sure

**Comment by Nish251103** [comment]
Done the needful Kindly check

**Comment by SVijayB** [comment]
Thanks for the PR! I've merged 👍

**Comment by Nish251103** [comment]
Okay thank you

**Pull request merged**
