### PR TITLE
Create Huffman_Coding.py

### PR DESCRIPTION
**Pull request by ASHMITA-DE**
Python implementation of Huffman Coding using Greedy Approach

### Related Issue

This PR closes #23

### Motivation and Context
Huffman Coding is a technique of compressing data to reduce its size without loss of data. It is generally useful to compress the data in which there are frequently occurring characters.
It follows a Greedy approach since it deals with generating minimum length prefix-free binary codes.
It uses variable-length encoding scheme for assigning binary codes to characters depending on how frequently they occur in the given text. 
Priority Queue is used for building the Huffman tree such that the character that occurs most frequently is assigned the smallest code and the one that occurs least frequently gets the largest code.
It follows this procedure: -
Create a leaf node for each character and build a min heap using all the nodes (The frequency value is used to compare two nodes in min heap)
Repeat Steps 3 to 5 while heap has more than one node
Extract two nodes, say x and y, with minimum frequency from the heap
Create a new internal node z with x as its left child and y as its right child. Also frequency(z)= frequency(x)+frequency(y)
Add z to min heap
Last node in the heap is the root of Huffman tree

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by ASHMITA-DE** [comment]
Python Implementation of Huffman Coding.

**Comment by SVijayB** [comment]
Hey, thanks for the PR! Merged 👍 . Good work!!

**Comment by ASHMITA-DE** [comment]
> Hey, thanks for the PR! Merged 👍 . Good work!!

Thank you so much!

**Comment by ASHMITA-DE** [comment]
> Hey, thanks for the PR! Merged 👍 . Good work!!

@SVijayB , as per the new rules of Hacktoberfest 2020, could you please label this pull request as "hacktoberfest-accepted"? Thank you.

**Comment by SVijayB** [comment]
Hey, @ASHMITA-DE It is also considered towards progress if the pull request is merged.

**Comment by ASHMITA-DE** [comment]
> Hey, @ASHMITA-DE It is also considered towards progress if the pull request is merged.

Oh ok, thank you!

**Pull request merged**
